2016-01-12 19:46:26,954 [Thread-11:11464][base:170] [WARNING]- Not Found: /favicon.ico
2016-01-12 19:46:26,970 [Thread-12:6980][base:170] [WARNING]- Not Found: /favicon.ico
2016-01-12 20:13:54,494 [Thread-1:552][base:256] [ERROR]- Internal Server Error: /init_jieba/
Traceback (most recent call last):
  File "C:\NoneInstallationTools\Project\ninandemo\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\NoneInstallationTools\Project\ninandemo\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\NoneInstallationTools\Project\ninandemo\lib\site-packages\django\views\generic\base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\NoneInstallationTools\Project\ninandemo\ninandemo\1\demo\views.py", line 54, in get
    contents = sae_bucket.get_object_contents(file_)
  File "<string>", line 3, in get_object_contents
  File "C:\NoneInstallationTools\Project\ninandemo\lib\site-packages\sae\storage.py", line 156, in get_object_contents
    raise Error(404, 'Not Found')
Error: (404, 'Not Found')
